CREATE TABLE application."user" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   last_modified_at TIMESTAMP WITHOUT TIME ZONE,
   firstname VARCHAR(255),
   lastname VARCHAR(255),
   email VARCHAR(255),
   password VARCHAR(255),
   CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE application.role (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   last_modified_at TIMESTAMP WITHOUT TIME ZONE,
   role VARCHAR(255),
   user_id INTEGER,
   CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE application.role ADD CONSTRAINT FK_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES application."user" (id);

CREATE TABLE application.token_info (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   last_modified_at TIMESTAMP WITHOUT TIME ZONE,
   token VARCHAR(255),
   token_type VARCHAR(255),
   revoked BOOLEAN NOT NULL,
   expired BOOLEAN NOT NULL,
   user_id INTEGER,
   CONSTRAINT pk_token_info PRIMARY KEY (id)
);

ALTER TABLE application.token_info ADD CONSTRAINT uc_token_info_token UNIQUE (token);
ALTER TABLE application.token_info ADD CONSTRAINT FK_TOKEN_INFO_ON_USER FOREIGN KEY (user_id) REFERENCES application."user" (id);

CREATE TABLE category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   last_modified_at TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   description VARCHAR(255),
   user_id INTEGER,
   CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE category ADD CONSTRAINT FK_CATEGORY_ON_USERID FOREIGN KEY (user_id) REFERENCES application."user" (id);

CREATE TABLE todo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   last_modified_at TIMESTAMP WITHOUT TIME ZONE,
   title VARCHAR(255),
   description VARCHAR(255),
   start_date TIMESTAMP WITHOUT TIME ZONE,
   done BOOLEAN NOT NULL,
   favorite BOOLEAN NOT NULL,
   category_entity_id BIGINT,
   CONSTRAINT pk_todo PRIMARY KEY (id)
);

ALTER TABLE todo ADD CONSTRAINT FK_TODO_ON_CATEGORYENTITYID FOREIGN KEY (category_entity_id) REFERENCES category (id);